server:
  port: 3344

spring:
  application:
    name:  lwohvye-spring-cloud-config
  cloud:
    config:
      server:
       git:
        uri: git@github.com:lWoHvYe/spring-cloud-lwohvye-config.git  #GitHub上面的git仓库名字

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: lwohvye-spring-cloud-config
    prefer-ip-address: true     #访问路径可以显示IP地址
